require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'source/feed.xml.builder'
    - 'source/tag.html.erb'

Layout/LineLength:
  Max: 80

Style/Documentation:
  Enabled: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/StringLiterals:
  EnforcedStyle: double_quotes
