inherit_from: .rubocop.yml

Layout/ExtraSpacing:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Semicolon:
  Enabled: false

# The settings above are specific to this project
# The settings below are from the repo below:
# https://github.com/edward-mb/finance-tracker/blob/master/.ruumba.yml
# Rubocop often incorrectly flags code extracted from ERB files.
# Hence, the settings below.

Layout/BlockAlignment:
  Enabled: false

Layout/LeadingEmptyLines:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false

Layout/SpaceAfterColon:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false

Layout/SpaceBeforeComment:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/SpaceBeforeSemicolon:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Lint/Void:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
